language: java
jdk:
  - openjdk8

jobs:
  include:
    - stage: build
      install: ./gradlew setupCiWorkspace -S
      script: ./gradlew build
    - stage: checkstyle
      install: echo "skipping default ./gradlew assemble"
      script: ./gradlew checkstyle

env:
  global:
    TERM=dumb
